// components/home/HeroSection.tsx
import Link from 'next/link'
import { ArrowDown, BookOpen, BriefcaseBusiness } from 'lucide-react'
import { Terminal } from '@/components/workspace/Terminal'
import { profile } from '@/lib/data/profile'

export function HeroSection({ projectCount, postCount }: { projectCount: number; postCount: number }) {
  return (
    <section className="workspace-bg relative overflow-hidden px-4 py-16 sm:px-6 sm:py-20 md:py-24">
      <div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[0.88fr_1.12fr]">
        <div>
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-secondary/30 bg-light/70 px-3 py-1.5">
            <span className="h-2 w-2 rounded-full bg-highlight" />
            <span className="text-xs text-text-light sm:text-sm">{profile.availability}</span>
          </div>

          <h1 className="glow mb-5 text-4xl font-bold tracking-tight text-text sm:text-5xl lg:text-6xl">
            Henrique <span className="text-highlight">Marino</span>
          </h1>
          <p className="mb-6 max-w-2xl text-lg leading-relaxed text-text-light sm:text-xl">{profile.headline}</p>
          <p className="mb-8 max-w-2xl text-sm leading-relaxed text-text-light sm:text-base">{profile.summary}</p>

          <div className="flex flex-col gap-3 sm:flex-row">
            <Link href="/projects" className="inline-flex items-center justify-center gap-2 rounded-md bg-secondary px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-accent">
              <BriefcaseBusiness className="h-4 w-4" aria-hidden="true" />
              Ver projetos
            </Link>
            <Link href="/blog" className="inline-flex items-center justify-center gap-2 rounded-md border border-secondary px-5 py-3 text-sm font-semibold text-text transition-colors hover:bg-secondary">
              <BookOpen className="h-4 w-4" aria-hidden="true" />
              Ler artigos
            </Link>
            <Link href="#skills" className="inline-flex items-center justify-center gap-2 rounded-md px-5 py-3 text-sm font-semibold text-text-light transition-colors hover:text-highlight">
              <ArrowDown className="h-4 w-4" aria-hidden="true" />
              Explorar workspace
            </Link>
          </div>
        </div>

        <Terminal projectCount={projectCount} postCount={postCount} />
      </div>
    </section>
  )
}

// components/HeroSection.vue
<template>
  <section class="gradient-bg min-h-screen flex items-center pt-20 pb-10 md:pt-32 md:pb-20 relative overflow-hidden">
    <div class="absolute inset-0 opacity-10">
      <div class="absolute top-1/4 left-1/4 w-64 h-64 bg-highlight rounded-full blur-3xl"></div>
      <div class="absolute bottom-1/4 right-1/4 w-64 h-64 bg-accent rounded-full blur-3xl"></div>
    </div>

    <div class="container mx-auto px-4 sm:px-6 relative z-10">
      <div class="max-w-3xl mx-auto">
        <div class="text-center mb-8 sm:mb-12">
          <div class="inline-flex items-center mb-4 sm:mb-6 px-3 py-1 sm:px-4 sm:py-2 rounded-full bg-light border border-secondary border-opacity-30">
            <span class="w-2 h-2 bg-highlight rounded-full pulse-dot mr-2"></span>
            <span class="text-xs sm:text-sm text-text-light">
              {{ t('hero.available') }}
            </span>
          </div>

          <h1 class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 sm:mb-6 glow">
            Henrique <span class="text-highlight">Marino</span>
          </h1>

          <p class="text-lg sm:text-xl text-text-light mb-8 sm:mb-12 max-w-2xl mx-auto">
            {{ t('hero.subtitle') }}
          </p>
        </div>

        <Terminal />

        <div class="flex flex-col sm:flex-row justify-center gap-4 mt-8 sm:mt-12">
          <a
            href="#projetos"
            class="bg-secondary hover:bg-accent text-white font-semibold py-3 px-6 rounded-lg transition-colors text-center"
            @click.prevent="scrollToSection('#projetos')"
          >
            {{ t('hero.viewProjects') }}
          </a>
          <a
            href="#contato"
            class="bg-transparent border border-secondary hover:bg-secondary text-white font-semibold py-3 px-6 rounded-lg transition-colors text-center"
            @click.prevent="scrollToSection('#contato')"
          >
            {{ t('hero.contact') }}
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const { t } = useLanguage()
const { scrollToSection } = useScroll()
</script>
