// components/home/ProjectsSection.tsx
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { ProjectCard } from '@/components/content/ProjectCard'
import { SectionHeading } from '@/components/ui/SectionHeading'
import type { Project } from '@/lib/content/types'

export function ProjectsSection({ projects }: { projects: Project[] }) {
  return (
    <section id="projects" className="bg-dark px-4 py-16 sm:px-6 sm:py-24">
      <div className="mx-auto max-w-6xl">
        <SectionHeading
          eyebrow="projects/"
          title="Projetos em destaque"
          description="Cada projeto tem uma página com o contexto, a stack e as principais decisões técnicas."
        />

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {projects.map((project) => (
            <ProjectCard key={project.slug} project={project} />
          ))}
        </div>

        <div className="mt-10 text-center">
          <Link href="/projects" className="inline-flex items-center gap-2 rounded-md border border-secondary px-5 py-3 text-sm font-semibold hover:bg-secondary">
            Abrir todos os projetos
            <ArrowRight className="h-4 w-4" aria-hidden="true" />
          </Link>
        </div>
      </div>
    </section>
  )
}

// components/ProjectsSection.vue
<template>
  <section id="projetos" class="bg-dark py-16 sm:py-24">
    <div class="container mx-auto px-4 sm:px-6">
      <div class="max-w-5xl mx-auto">
        <div class="text-center mb-12 sm:mb-16">
          <h2 class="section-title text-2xl sm:text-3xl md:text-4xl font-bold mb-4">
            {{ t('projects.title') }}
          </h2>
          <p class="text-text-light max-w-2xl mx-auto text-sm sm:text-base">
            {{ t('projects.subtitle') }}
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
          <ProjectCard
            v-for="project in projects"
            :key="project.id"
            :project="project"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const { t } = useLanguage()
const { projects } = useProjects()
</script>
